import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { HardhatUserConfig, task } from "hardhat/config";
import "@nomicfoundation/hardhat-ethers";
import "@nomicfoundation/hardhat-chai-matchers";
import "solidity-coverage";

/** The SDK deploys and calls the contract on Hedera with this ABI and bytecode; nobody copies them by hand. */
export const GENERATED_ARTIFACT = path.resolve(__dirname, "../sdk/generated/AccreditationRegistry.ts");

export function renderArtifact(abi: unknown, bytecode: string): string {
  return [
    "// Generated by `yarn codegen` (packages/hardhat) from contracts/AccreditationRegistry.sol. Do not edit.",
    `export const ACCREDITATION_REGISTRY_ABI = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
    `export const ACCREDITATION_REGISTRY_BYTECODE = "${bytecode}";`,
    "",
  ].join("\n");
}

task("codegen", "Writes packages/sdk/generated/AccreditationRegistry.ts from the compiled contract")
  .addFlag("check", "Fail if the committed file is stale instead of writing it")
  .setAction(async ({ check }: { check: boolean }, hre) => {
    await hre.run("compile", { quiet: true });
    const artifact = await hre.artifacts.readArtifact("AccreditationRegistry");
    const rendered = renderArtifact(artifact.abi, artifact.bytecode);
    if (check) {
      const committed = await readFile(GENERATED_ARTIFACT, "utf8").catch(() => "");
      if (committed.replace(/\r\n/g, "\n") !== rendered) {
        throw new Error("packages/sdk/generated/AccreditationRegistry.ts is stale: run `yarn codegen`.");
      }
      return;
    }
    await writeFile(GENERATED_ARTIFACT, rendered);
  });

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.28",
    // Hedera's EVM supports Cancun.
    settings: { evmVersion: "cancun", optimizer: { enabled: true, runs: 200 } },
  },
  // Only the in-process network: the contract is deployed and called on Hedera by @sh/sdk (any operator key curve).
  defaultNetwork: "hardhat",
};

export default config;
