#!/usr/bin/env node
// Self-check of the bounty eligibility gate (docs/bounty-rules.md, Part A). Every requirement runs under its own id and
// is reported as PASS, FAIL, SKIP or BLOCKED, so a failure names the requirement instead of a bare "failed".
// CI runs exactly this script (.github/workflows/ci.yml). See docs/self-check.md.
//
//   node scripts/self-check.mjs [--only <id,...>] [--skip <id,...>] [--list]
//
// Dependency-free on purpose: it must run before `yarn install`, which is itself one of the requirements.
import { execFileSync, spawn } from "node:child_process";
import { appendFileSync, existsSync, readFileSync, statSync } from "node:fs";
import net from "node:net";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const listOpt = name => {
  const i = args.indexOf(name);
  return i === -1 ? [] : (args[i + 1] ?? "").split(",").filter(Boolean);
};
const inCi = Boolean(process.env.CI);
const inGitHub = process.env.GITHUB_ACTIONS === "true";
const OUTPUT_TAIL_LINES = 40;
const BOOT_TIMEOUT_MS = 90_000;
const ROUTE_TIMEOUT_MS = 30_000;
const CORE_ROUTES = ["/", "/api/health"];

// Scanned over the working tree even without gitleaks; the Hedera DER rules mirror .gitleaks.toml, which also covers the
// git history. Full-length keys only: tests carry truncated DER prefixes to prove redaction, and those must not match.
const SECRET_PATTERNS = [
  { name: "Hedera ED25519 private key (DER)", re: /302e020100300506032b657004220420[0-9a-f]{64}/i },
  { name: "Hedera ECDSA secp256k1 private key (DER)", re: /3030020100300706052b8104000a04220420[0-9a-f]{64}/i },
  {
    name: "raw private key assigned to a *_KEY variable",
    re: /\b[A-Z0-9_]*(?:PRIVATE|OPERATOR|DEPLOYER)_KEY\b["']?\s*[:=]\s*["']?(?:0x)?[0-9a-f]{64}(?![0-9a-f])/i,
  },
  { name: "PEM private key", re: /-----BEGIN (?:[A-Z]+ )?PRIVATE KEY-----/ },
];
const MAX_SCAN_BYTES = 1_000_000;
const YARN_BUILTINS = new Set([
  "install",
  "workspace",
  "workspaces",
  "add",
  "remove",
  "up",
  "dlx",
  "run",
  "why",
  "dedupe",
]);

const read = file => readFileSync(path.join(root, file), "utf8");
// Windows resolves `yarn` to `yarn.cmd`, which `spawn` only finds through a shell.
const WINDOWS = process.platform === "win32";

const git = gitArgs => execFileSync("git", gitArgs, { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
const publishableFiles = () =>
  git(["ls-files", "-co", "--exclude-standard", "-z"])
    .split("\0")
    .filter(f => f && existsSync(path.join(root, f)));
const onPath = cmd => {
  try {
    execFileSync(cmd, ["version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
};

/** Runs a command with its output captured; returns { status, output }. */
function run(cmd, cmdArgs, env = {}) {
  return new Promise(resolve => {
    const child = spawn(cmd, cmdArgs, {
      cwd: root,
      env: { ...process.env, FORCE_COLOR: "0", ...env },
      stdio: ["ignore", "pipe", "pipe"],
      shell: WINDOWS,
    });
    let output = "";
    child.stdout.on("data", d => (output += d));
    child.stderr.on("data", d => (output += d));
    child.on("error", e => resolve({ status: 127, output: `${output}${e.message}\n` }));
    child.on("close", status => resolve({ status: status ?? 1, output }));
  });
}

/** A requirement that is exactly one command. */
const command = (cmd, cmdArgs, hint) => async () => {
  const { status, output } = await run(cmd, cmdArgs);
  return status === 0
    ? { ok: true, output }
    : { ok: false, detail: `\`${[cmd, ...cmdArgs].join(" ")}\` exited with ${status}.`, output, hint };
};

function freePort() {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.unref();
    server.on("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const { port } = server.address();
      server.close(() => resolve(port));
    });
  });
}

async function get(url) {
  const res = await fetch(url, { signal: AbortSignal.timeout(ROUTE_TIMEOUT_MS), redirect: "manual" });
  return { status: res.status, body: await res.text() };
}

const requirements = [
  {
    id: "toolchain",
    gate: "GATE-08",
    title: "Node.js satisfies engines.node and Yarn is available",
    run: command("node", ["scripts/doctor.mjs"], "Install Node.js >= engines.node and run `corepack enable`."),
  },
  {
    id: "manifest",
    gate: "GATE-09",
    title: "template.json present and valid for create-scaffold-hbar",
    run: async () => {
      if (!existsSync(path.join(root, "template.json")))
        return {
          ok: false,
          detail: "template.json is missing.",
          hint: "A project generated by the CLI no longer has it; run with `--skip manifest` there.",
        };
      return command("node", ["scripts/validate-template.mjs"], "Fix template.json as listed above.")();
    },
  },
  {
    id: "docs",
    gate: "GATE-10/11",
    title: "README.md and AGENTS.md present; every `yarn <script>` they cite exists",
    run: async () => {
      const problems = [];
      const scripts = JSON.parse(read("package.json")).scripts ?? {};
      for (const file of ["README.md", "AGENTS.md"]) {
        if (!existsSync(path.join(root, file)) || read(file).trim().length === 0) {
          problems.push(`${file} is missing or empty.`);
          continue;
        }
        for (const [n, line] of read(file).split("\n").entries()) {
          if (/^\s*(Planned|Planejad)/i.test(line)) continue;
          for (const [, script] of line.matchAll(/`yarn ([a-z][\w:-]*)/g)) {
            if (!scripts[script] && !YARN_BUILTINS.has(script))
              problems.push(`${file}:${n + 1} cites \`yarn ${script}\`, which is not a root script.`);
          }
        }
      }
      return problems.length === 0
        ? { ok: true }
        : {
            ok: false,
            detail: problems.join("\n"),
            hint: "Add the script, or move it to the Planned line.",
          };
    },
  },
  {
    id: "license",
    gate: "GATE-03",
    title: "LICENSE is MIT",
    run: async () =>
      existsSync(path.join(root, "LICENSE")) && /^MIT License/.test(read("LICENSE"))
        ? { ok: true }
        : { ok: false, detail: 'LICENSE is missing or does not start with "MIT License".' },
  },
  {
    id: "no-env",
    gate: "GATE-19",
    title: "No .env file committed or committable (only .env.example)",
    run: async () => {
      const problems = publishableFiles()
        .filter(f => /^\.env(\..+)?$/.test(path.basename(f)) && path.basename(f) !== ".env.example")
        .map(f => `${f} is tracked or not ignored.`);
      try {
        git(["check-ignore", "-q", "--no-index", ".env"]);
      } catch {
        problems.push(".gitignore does not ignore .env.");
      }
      return problems.length === 0
        ? { ok: true }
        : {
            ok: false,
            detail: problems.join("\n"),
            hint: "`git rm --cached <file>`, rotate any credential it held, and keep .env in .gitignore.",
          };
    },
  },
  {
    id: "secrets",
    gate: "GATE-19",
    title: "No committed secrets (gitleaks over the git history + Hedera key patterns)",
    run: async () => {
      const findings = [];
      for (const file of publishableFiles()) {
        const abs = path.join(root, file);
        if (statSync(abs).size > MAX_SCAN_BYTES) continue;
        const text = readFileSync(abs, "utf8");
        if (text.includes("\0")) continue;
        for (const [n, line] of text.split("\n").entries()) {
          for (const { name, re } of SECRET_PATTERNS) if (re.test(line)) findings.push(`${file}:${n + 1} ${name}`);
        }
      }
      const warnings = [];
      let output = "";
      if (onPath(process.env.GITLEAKS_BIN || "gitleaks")) {
        const scan = await run("node", ["scripts/secret-scan.mjs"]);
        output = scan.output;
        if (scan.status === 1) findings.push("`yarn secrets:scan` reported findings (listed in the output above).");
        else if (scan.status !== 0) findings.push(`\`yarn secrets:scan\` could not run (exit ${scan.status}).`);
      } else if (inCi) {
        findings.push("gitleaks is not installed; CI must install it.");
      } else {
        warnings.push(
          "gitleaks not found on PATH: only the Hedera key patterns ran. Install it (brew install gitleaks).",
        );
      }
      return findings.length === 0
        ? { ok: true, output, warnings }
        : {
            ok: false,
            detail: findings.join("\n"),
            output,
            hint: "Remove the secret from history, rotate it, and never commit real keys (AGENTS.md).",
          };
    },
  },
  {
    id: "install",
    gate: "GATE-15",
    title: "Clean install against the lockfile (yarn install --immutable)",
    run: command("yarn", ["install", "--immutable"], "Run `yarn install` and commit the updated yarn.lock."),
  },
  {
    id: "lint",
    gate: "GATE-16",
    title: "Lint passes with no warnings (yarn lint)",
    needs: ["install"],
    run: command("yarn", ["lint"], "Run `yarn lint` locally; `yarn format` fixes formatting."),
  },
  {
    id: "types",
    gate: "—",
    title: "Type check passes (yarn check-types)",
    needs: ["install"],
    run: command("yarn", ["check-types"]),
  },
  {
    id: "tests",
    gate: "—",
    title: "Unit tests pass (yarn test)",
    needs: ["install"],
    run: command("yarn", ["test"]),
  },
  {
    id: "build",
    gate: "GATE-17",
    title: "Production build passes (yarn build)",
    needs: ["install"],
    run: command("yarn", ["build"]),
  },
  {
    id: "boot",
    gate: "GATE-18",
    title: `App boots (yarn serve) and core routes return 200: ${CORE_ROUTES.join(", ")}`,
    needs: ["build"],
    run: async () => {
      const port = await freePort();
      const base = `http://127.0.0.1:${port}`;
      const server = spawn("yarn", ["serve"], {
        cwd: root,
        env: { ...process.env, PORT: String(port), FORCE_COLOR: "0" },
        stdio: ["ignore", "pipe", "pipe"],
        detached: !WINDOWS,
        shell: WINDOWS,
      });
      let output = "";
      let exited = false;
      server.stdout.on("data", d => (output += d));
      server.stderr.on("data", d => (output += d));
      server.on("close", () => (exited = true));
      const stop = () => {
        try {
          // The server is a process tree (yarn → next): stop all of it.
          if (WINDOWS) execFileSync("taskkill", ["/pid", String(server.pid), "/T", "/F"], { stdio: "ignore" });
          else process.kill(-server.pid, "SIGTERM");
        } catch {
          // already gone
        }
      };
      try {
        const deadline = Date.now() + BOOT_TIMEOUT_MS;
        let up = false;
        while (!up && !exited && Date.now() < deadline) {
          up = await get(base + "/").then(
            () => true,
            () => false,
          );
          if (!up) await new Promise(r => setTimeout(r, 1000));
        }
        if (!up)
          return {
            ok: false,
            detail: exited
              ? "`yarn serve` exited before answering."
              : `No answer on ${base} after ${BOOT_TIMEOUT_MS / 1000}s.`,
            output,
          };
        const problems = [];
        for (const route of CORE_ROUTES) {
          try {
            const { status, body } = await get(base + route);
            if (status !== 200) problems.push(`GET ${route} returned ${status}.`);
            else if (route.startsWith("/api/")) JSON.parse(body);
          } catch (e) {
            problems.push(`GET ${route} failed: ${e.message}`);
          }
        }
        return problems.length === 0
          ? { ok: true, output }
          : { ok: false, detail: problems.join("\n"), output, hint: "Reproduce with `yarn build && yarn serve`." };
      } finally {
        stop();
      }
    },
  },
];

if (args.includes("--list")) {
  for (const r of requirements) console.log(`${r.id.padEnd(10)} ${r.gate.padEnd(11)} ${r.title}`);
  process.exit(0);
}
const only = listOpt("--only");
const skip = listOpt("--skip");
const known = new Set(requirements.map(r => r.id));
for (const id of [...only, ...skip]) {
  if (!known.has(id)) {
    console.error(`Unknown requirement "${id}". Known: ${[...known].join(", ")}.`);
    process.exit(2);
  }
}

const tail = text => text.trimEnd().split("\n").slice(-OUTPUT_TAIL_LINES).join("\n");
const indent = (text, pad = "        ") => text.replace(/^/gm, pad);
const results = new Map();

console.log("Self-check: bounty eligibility gate (docs/bounty-rules.md, Part A)\n");
for (const [i, r] of requirements.entries()) {
  const label = `[${String(i + 1).padStart(2)}/${requirements.length}] ${r.id.padEnd(10)} ${r.gate.padEnd(11)}`;
  if ((only.length > 0 && !only.includes(r.id)) || skip.includes(r.id)) {
    results.set(r.id, { status: "SKIP", detail: "skipped by option" });
    console.log(`${label} SKIP  ${r.title}`);
    continue;
  }
  const failedNeed = (r.needs ?? []).find(n => ["FAIL", "BLOCKED"].includes(results.get(n)?.status));
  if (failedNeed) {
    results.set(r.id, { status: "BLOCKED", detail: `not run: "${failedNeed}" failed.` });
    console.log(`${label} BLOCKED  ${r.title} (needs ${failedNeed})`);
    continue;
  }
  const started = Date.now();
  let result;
  try {
    result = await r.run();
  } catch (e) {
    result = { ok: false, detail: `The check itself crashed: ${e.stack ?? e}` };
  }
  const seconds = ((Date.now() - started) / 1000).toFixed(1);
  const status = result.ok ? "PASS" : "FAIL";
  results.set(r.id, { ...result, status });
  console.log(`${label} ${status}  ${r.title} (${seconds}s)`);
  for (const w of result.warnings ?? []) console.log(`        warn: ${w}`);
  if (!result.ok) {
    if (result.output?.trim()) {
      if (inGitHub) console.log(`::group::${r.id}: full output`);
      console.log(indent(inGitHub ? result.output.trimEnd() : tail(result.output), "        | "));
      if (inGitHub) console.log("::endgroup::");
    }
    console.log(indent(result.detail ?? "failed."));
    if (result.hint) console.log(indent(`fix: ${result.hint}`));
  }
}

const failed = requirements.filter(r => ["FAIL", "BLOCKED"].includes(results.get(r.id).status));
console.log("\nSummary");
for (const r of requirements) {
  const { status, detail } = results.get(r.id);
  const line = `  ${status.padEnd(7)} ${r.id.padEnd(10)} ${r.gate.padEnd(11)} ${r.title}`;
  console.log(status === "FAIL" || status === "BLOCKED" ? `${line}\n${indent(detail ?? "")}` : line);
  if (inGitHub && status === "FAIL") {
    const message = (detail ?? "failed").replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
    console.log(`::error title=self-check ${r.id} (${r.gate})::${message}`);
  }
}
if (process.env.GITHUB_STEP_SUMMARY) {
  const rows = requirements.map(r => {
    const { status, detail } = results.get(r.id);
    const cell =
      status === "PASS" || status === "SKIP" ? "" : (detail ?? "").replace(/\|/g, "\\|").replace(/\n/g, "<br>");
    return `| ${status} | \`${r.id}\` | ${r.gate} | ${r.title.replace(/\|/g, "\\|")} | ${cell} |`;
  });
  appendFileSync(
    process.env.GITHUB_STEP_SUMMARY,
    [
      "### Self-check",
      "",
      "| Status | Requirement | Gate | Check | Detail |",
      "|---|---|---|---|---|",
      ...rows,
      "",
    ].join("\n"),
  );
}
console.log(
  failed.length === 0
    ? "\nAll requirements passed."
    : `\n${failed.length} requirement(s) failed: ${failed.map(r => r.id).join(", ")}.`,
);
process.exit(failed.length === 0 ? 0 : 1);
